refactor: reindent context script

diff --git a/files/bin/context b/files/bin/context
--- a/files/bin/context
+++ b/files/bin/context
@@ -4,35 +4,35 @@ CONTEXT_FILE="$HOME/.context"
 CURRENT_CONTEXT=$(awk -F "=" '/ENV_CONTEXT/{print $2}' "$CONTEXT_FILE" 2>/dev/null)
 
 if [[ ! -f "$CONTEXT_FILE" ]]; then
-  touch "$CONTEXT_FILE"
+	touch "$CONTEXT_FILE"
 fi
 
 if [[ $# -eq 0 ]]; then
-  echo "No argument supplied. Please provide a context:"
-  echo "Pass '1' for personal context"
-  echo "Pass '2' for work context"
-  echo
-  echo "Current context is \"$CURRENT_CONTEXT\""
-  exit 1
+	echo "No argument supplied. Please provide a context:"
+	echo "Pass '1' for personal context"
+	echo "Pass '2' for work context"
+	echo
+	echo "Current context is \"$CURRENT_CONTEXT\""
+	exit 1
 fi
 
 case $1 in
 1)
-  CONTEXT="personal"
-  ;;
+	CONTEXT="personal"
+	;;
 2)
-  CONTEXT="work"
-  ;;
+	CONTEXT="work"
+	;;
 *)
-  echo "Error: Invalid argument. Please provide either '1' for personal or '2' for work."
-  exit 1
-  ;;
+	echo "Error: Invalid argument. Please provide either '1' for personal or '2' for work."
+	exit 1
+	;;
 esac
 
 if [[ "$CONTEXT" == "$CURRENT_CONTEXT" ]]; then
-  echo "The context is already set to $CONTEXT."
-  exit 0
+	echo "The context is already set to $CONTEXT."
+	exit 0
 fi
 
-echo "export ENV_CONTEXT=$CONTEXT" "${CONTEXT_FILE:-$HOME/.context}" >!
+echo "set -gx ENV_CONTEXT $CONTEXT" >"${CONTEXT_FILE:-$HOME/.context}"
 echo "Context updated to $CONTEXT"
